### ISSUE TITLE
All links are broken in News default config

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#104]
When running News, all links are broken in the default config.

Perhaps this may have something to do with recent commits changing all URLs to being absolute? Is there any particular reasoning to forcing absolute URLs?

I know that I could just fix the config to point to a valid domain name, but it's also nice to be able to spin up a temporary News instance for testing things, and it's a bit off putting when things don't work out of the box.

**Comment by akkartik** [comment]
Oh I see, the links all point to example.com. Yes, I agree that we can improve on this experience. @kennethrapp, what was your reasoning for making links absolute? Let's see if we can't achieve those improvements with a slight tweak.

**Comment by hjek** [comment]
Having more than one domain for a News page is not possible with absolute URLs.

Who would do that then? Perhaps people who host a page as a Tor hidden service would have a separate .onion URL for the same News page.

It's cool with the new contributions, but I think this particular one with the absolute URLs is questionable.

**Comment by akkartik** [comment]
For me it's not so much about absolute or relative links. Every site will have its own conventions, it just has to be internally consistent. The HN app in this repo is just an example, and the entire repo is pretty DIY, so Tor hidden services will have to be done in a self-service manner. But yes, broken links do prevent this repo from showing off its example app to the fullest extent.

**Comment by hjek** [comment]
Agreed.

 But right now it's inconsistent as there are still relative links, for example every call to `underlink`.

**Comment by hjek** [comment]
I do really appreciate that Anarki lets anyone push code, and it works great.

I'm going to also use that principle to get rid of this breakage, as it is clearly not too well thought out, as can be seen in this snippet:

    (abs-link site-url* "anarki" "http://github.com/arclanguage/anarki"))))

I'm just doing a bit of quality control here.

**Comment by hjek** [comment]
Also memoisation has been disabled for `item-link`, apparently for it to look similar to other link definitions. Or is there another reason?

Sorry, my intention is not to be overly critical here, and I am sorry if it comes across that way. I'd like to hear what the intention is behind these commits.

**Comment by akkartik** [comment]
Yes, definitely, feel free to push more edits. We can always revisit if @kennethrapp or someone else points out issues we missed.

**Comment by kennethrapp** [comment]
Making links absolute prevents urls generated in the code from breaking if the base directory isn't what is expected - which I've seen happen in other frameworks often enough that I avoid relative urls in code by habit. Also, having form URLS be absolute should prevent browsers from complaining about the insecure field. My general thought was that if the server is running securely, every url on the page should have an explicit, absolute url.

**Comment by hjek** [comment]
> Making links absolute prevents urls generated in the code from breaking if the base directory isn't what is expected
I agree that it is important not to break the links.

But, you are aware that your commit broke News in the default setup, right? Also, it doesn't make sense to throw in the site name before links that are *are already absolute*, like this:  `(abs-link site-url* "anarki" "http://github.com/arclanguage/anarki"))`. So, if the goal is to "prevent goal from breaking", then it is actually not a good change, because the code worked before the change, and was broken :boom: after the change. Agree?

> Also, having form URLS be absolute should prevent browsers from complaining about the insecure field.

No, sorry, that is just wrong! It won't make your site "insecure" having relative links. [Browser security warnings about insecure password fields happen when the connection is not encrypted.](https://www.troyhunt.com/bypassing-browser-security-warnings-with-pseudo-password-fields/) If you want to make your site secure, then get a server certificate and redirect all HTTP requests to HTTPS. [I've put an example Nginx configuration that does exactly that to this repo.](https://github.com/arclanguage/anarki/blob/master/extras/news.nginx.conf) Feel free to use it, and feel free to ask if you have any questions about securing your site.

**Comment by kennethrapp** [comment]
Since the default base url is an example, I assumed it was acceptable to expect people to change it, and in testing it works fine with localhost. I shouldn't have made that assumption, so I apologize. 

>No, sorry, that is just wrong! It won't make your site "insecure" having relative links.

No, but browsers will put up an alert warning about it. It happens on HN and arclanguage.org and practically nowhere else, and that's the issue I was trying to fix.

**Comment by hjek** [comment]
The security warnings happen on arclanguage.org because they don't use HTTPS (which is brain dead [but the admins don't care](http://arclanguage.org/item?id=20245)).

It has absolutely nothing to do with relative links, I promise you. Can you please find *any* web site that describes how relative links could trigger a browser security warning.

(If you got a warning on HN, you might actually want to take that seriously, as you might be MITM'd.)

This absolute-links-are-secure is [hocus pocus](https://www.troyhunt.com/dont-take-security-advice-from-seo-experts-or-psychics-neil-patel/).

I don't know what browser you are using, but perhaps you could copy-paste this error you get here, when you use relative links on a web site, and we can walk through it together?

**Comment by kennethrapp** [comment]
No, I'm just going to take my lumps and accept I was wrong and that this commit wasn't as useful as I thought it would be. There's no need to belabor the point.
