### ISSUE TITLE
News titled left in Firefox

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#105]
Recently News has started to look strange in Firefox: Too narrow and aligned to the left. Looks like a CSS issue.

![screenshot from 2018-08-13 00-20-57](https://user-images.githubusercontent.com/11958965/44007506-dc0b40f2-9e8e-11e8-8d66-5100a135cd85.png)

(Firefox in safe mode, no plugins, etc)

**Comment by hjek** [comment]
I think it might be a good idea to test the changes a little bit before pushing them, maybe just in two different browsers?

**Comment by akkartik** [comment]
I did see that and assumed it was because of not finding the css file, again because of the absolute link being broken. Possible?

**Comment by hjek** [comment]
When the CSS fails to load, News looks quite a bit different, e.g. it has a serif font and blue hyperlinks. So the CSS did load. It was just broken.

**Comment by rocketnia** [comment]
Thanks for fixing this. :)
