### ISSUE TITLE
News slowness

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#106]
Some recent change has made News incredibly slow. Front page takes 12-13 seconds to load on my server now. Used to be about 1/10 of that.

Could just be my server being slow, but it happened right after doing a pull.

**Comment by akkartik** [comment]
Are you resting with data, @hjek? My testing is sadly restricted on that score.

**Comment by hjek** [comment]
>2000 stories and comments.

Maybe it would be useful when testing to have a function that adds n stories with m comments or something.

**Comment by hjek** [comment]
I can confirm that News has gone ~10 times slower since Anarki commit f9084477a343c566e48099dad0667e799600cb0b that I was running previously. Might do a git bisect to find out what happened.

**Comment by hjek** [comment]
> My testing is sadly restricted on that score.

`(for i 0 (<= i 1000) ++.i (create-story "https://example.com" "Hello" "" "someone" "127.0.0.1"))`

**Comment by hjek** [comment]
Looks like it could have to do with `dynamic-require`:

````
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
b2a7cf9c7a6dd7e0adc3caf9e439a10a3f241ab9
a39135ce63720c4fde99a44e8cc8ab24e2101149
We cannot bisect more!
````

**Comment by hjek** [comment]
That makes sense though. This `dynamic-require` makes Arc load several libraries for each random string. And News uses a lot of random strings in its URLs.

**Comment by hjek** [comment]
Yes, it was `dynamic-require` that was causing the problems. @rocketnia, am I breaking anything you were working on by loading libraries in advance?

**Comment by rocketnia** [comment]
Ah, I commented on commit https://github.com/arclanguage/anarki/commit/cd781ad7e6ca599a5513332c12745f976cd783f9 before seeing this thread. You broke only the things that were documented in the comments you commented out. :-p Namely, you broke compatibility with Racket versions pre-6.11. This might just mean we need to update .travis.yml's reference to Racket 6.3 and the readme's reference to Racket 6.8.

**Comment by rocketnia** [comment]
I mean, we could update both of those references from 6.3/6.8 to 6.11.

**Comment by hjek** [comment]
Cool. I vote for breaking compatibility :bomb:
