### ISSUE TITLE
Documentation website based on docstrings

### ISSUE THREAD

**Issue by rocketnia** [arclanguage/anarki#112]
Anarki's /lib/ directory already has a bunch of documentation in the form of docstrings and `(examples ...)`. These can be accessed from the REPL, but it would be pretty nice if they could be built into a documentation website. This would be a great way to keep the website's documentation up to date.

The website could have a page for every file in libs.arc, with a link to the GitHub file tree (maybe called "Edit this library!" 😃). If a file has docstrings or examples, the page can display those in a nicely formatted way. Otherwise, it can display the full code of the file in "the code is the spec" style.

Anarki already has code for building the Arc 3.1 documentation. If I recall correctly, that code is based on something pretty similar to docstrings. It's possible that code can be adapted to work for Anarki.

**Comment by rocketnia** [comment]
I took a look at the https://github.com/arclanguage/arclanguage.github.io repo where the Arc 3.1 documentation builder is. That's quite a bit of code that I'm not sure would be easy to adapt to Anarki.

Instead, I've just taken my own stab at it in https://github.com/arclanguage/anarki/commit/6a2bda79cc480a04898ed6657402a09ef6cf40f4. The script build-web-help.arc runs the tests (as an easy way to load the docstrings) and generates file called help.html containing a single page. Docstring cross-references of the form `[[foo]]` are turned into hyperlinks to the relevant location on the page.

**Comment by rocketnia** [comment]
Hey @akkartik, it's okay if I overwrite the gh-pages branch, right? I'm thinking I'll have the Travis CI script deploy there automatically based on commits to the master branch. That way we can have the docstrings turn into hyperlinked documentation automatically.

**Comment by rocketnia** [comment]
I ask 'cause you did commit one simple "hello world" there a few years ago. :)

Anyhow, I'm about to sleep, but I'll probably get back to this project in the next day or so.

**Comment by akkartik** [comment]
Totally fine!

**Comment by rocketnia** [comment]
I set up a script that seems to be successfully populating the `gh-pages` branch when there are commits to `master`.

I don't see [the help page](https://arclanguage.github.io/anarki/help/) online yet, but I'm also not seeing any GitHub pages errors in the repository settings. I did just make my designated one machine user, @rocketniabot, to make these commits, and it doesn't have a public email address, so maybe it's an email verification delay of some sort. Or maybe it's because I wiped the old `gh-pages` branch today.

I think I'll take a break and see if it comes online later. If not, maybe the next push to `master` will do it, or maybe it'll start working once someone with a public email address pushes to the `gh-pages` branch manually.

**Comment by rocketnia** [comment]
Point by point:

* ℹ️ It turns out the page contained the docstrings related to ac.rkt and arc.arc definitions all along. Some of the things it references from ac.rkt just haven't had `(document builtin ...)` entries written yet. (The list of broken links is currently `defset`, `mapeach`, `list`, `<`, `+`, `aform`, `uniq`, `arform`, and `write`. Not all of those are from ac.rkt.)

* ✔️ It does appear that the CI script is successfully pushing to GitHub Pages.

* ✔️ I've added a link from https://arclanguage.github.io/.

**Comment by rocketnia** [comment]
I opened [an Arc Forum thread](http://arclanguage.org/item?id=20595) in which I discuss some security recommendations for this automated deployment script, as well as describing why a help entry entry may or may not appear on the help page.

**Comment by akkartik** [comment]
http://arclanguage.org/item?id=20595

**Comment by hjek** [comment]
This is cool, and the CSS looks great, too.

I wish this doc functionality wasn't so tied in with Github though :partly_sunny:

**Comment by rocketnia** [comment]
Yeah, the automatic pushing isn't a critical part of this repo, but it is one more thing that associates the repo with GitHub.
