### ISSUE TITLE
Deprecated HTML tags and attributes

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#115]
**News** uses some deprecated HTML tags, like `<center>`, and tag attributes for styling (instead of CSS). It does mean that News better than most pages in web browsers that don't support CSS, such as **Links2**. But having the styling baked into the code means that it's fairly difficult to change it. And to have different themes, you'd effectively have to maintain two versions of `news.arc` rather than two versions of `news.css`.

**Comment by kennethrapp** [comment]
More or less done, and themes will work as soon as I finish writing a dark theme.
