### ISSUE TITLE
install fails due to missing dll

### ISSUE THREAD

**Issue by kennethrapp** [arclanguage/anarki#143]
Tried a fresh install of Anarki on Windows following the instructions in the readme, and running the arc shell fails with the following error:

`ffi-lib: couldn't open "libuuid-1.dll" (The specified module could not be found.; errid=126)`

Installing the libuuid package through raco also fails with the same error.

**Comment by shawwn** [comment]
I was afraid of that. If you open ac.rkt and comment out the lines related to "uuid", does anarki load successfully?

**Comment by shawwn** [comment]
@kennethrapp Ok, I've pushed a fix via 37645b484d486184b967bc0bb5fcd9f5554074e8

Are you able to run anarki on windows? I'd like to improve the cross-platform support sometime. If you run into other problems let me know.

**Comment by kennethrapp** [comment]
The windows install works now.
