### ISSUE TITLE
"collection not found for module path: sha"

### ISSUE THREAD

**Issue by zck** [arclanguage/anarki#155]
I've been setting up a new computer, and just got things working. Arc3.2 starts up fine, but when I try to start up Anarki, I get this error:

```
$ ./arc.sh 
initializing arc.. (may take a minute)
standard-module-name-resolver: collection not found
  for module path: sha
  collection: "sha"
  in collection directories:
   /home/zck/.racket/6.12/collects
   /usr/share/racket/collects
   ... [159 additional linked and package directories]
  context...:
   show-collection-err
   standard-module-name-resolver
   /home/zck/programs/arc/anarki/ac.rkt:1361:0: aload1
   /usr/share/racket/collects/racket/private/kw.rkt:446:14:  recur
   /usr/share/racket/collects/racket/private/kw.rkt:446:14:  require
   /home/zck/programs/arc/anarki/ac.rkt:1361:0: aload1
   /usr/share/racket/collects/racket/private/promise.rkt:96:0: force/generic
```

I'm on commit 0799c96c2ea4dc76bcdfcee0e257850cb28ad4b8.

**Comment by akkartik** [comment]
Unfortunately you have to run `raco pkg install sha` as of a couple of months ago. It's worth going over the instructions in the Readme if you haven't in a while. Let me know if that fixes it.

**Comment by zck** [comment]
Yep, that did it! Sorry I missed the Readme update. It has been a while since I've pulled the latest.

Thanks!
