### ISSUE TITLE
include the test file?

### ISSUE THREAD

**Issue by kennethrapp** [arclanguage/anarki#159]
Is there a reason we don't include zck's test suite in /lib, instead of requiring people to install mercurial just for that one .arc file?  

Also, while it's on my mind, would it be possible or preferable to include racket dependencies like sha directly (as, maybe, a separate library folder for racket) instead of having to go through raco?

**Comment by zck** [comment]
It's a method of proselytizing to encourage mercurial use.

Seriously, though, I guess that should be fine. It would certainly make testing easier. We'd just have to make sure to update the suite periodically -- although I'm not updating it much anymore.

**Comment by akkartik** [comment]
I wish there was something like `git submodule` that also supported non-git.

**Comment by kennethrapp** [comment]
done: #160
