### ISSUE TITLE
create project commit/GAnarchy support

### ISSUE THREAD

**Issue by SoniEx2** [arclanguage/anarki#169]
https://ganarchy.autistic.space/project/385e734a52e13949a7a5c71827f6de920dbfea43/

a project commit is just a commit with a message like

```text
[Project] Project Name

Short description
```

**Comment by akkartik** [comment]
Hi @SoniEx2, I don't quite follow what GAnarchy does, but the goal of "giving forks of a project the same visibility as the original repo" definitely resonates. I'd love to give forks of this project more "first class" status. Can you answer some questions about how GAnarchy works?

* Once I make a commit here, what happens next? Is there some list of projects that this repo shows up on? Will forks show up there as well?
* It sounds like you're crawling different locations like GitHub and so on. Is the list of places you crawl available somewhere?
* If somebody hosts a fork somewhere that your crawler can't get to, is there a way to register it in a self-service manner?
* To make a commit I have to make a change to the repo. People may not want to bundle file changes with something unrelated. Is there an alternative way to register, like creating a file with a special name in the repository?

Looking forward to hearing more. This sounds like an interesting project.

**Comment by SoniEx2** [comment]
you can use `git commit --allow-empty`.

the commit only allows grouping forks together under the same project. the reason to use a commit is the cryptographic nature of the commit log. by sticking the metadata in the commit, a ganarchy instance doesn't need to be manually configured with the project details other than the commit itself and the participating repos.

ganarchy doesn't crawl anything. I wanted to integrate it with gitea but I haven't heard anything back from them about it. you have to add repos manually, but in an ideal world you'd add instances instead. (this is still useful to prevent malware from spreading tho.)

**Comment by akkartik** [comment]
Done. Out of curiosity, is it possible to revise project commits? If I add a second project commit at a later date, will GAnarchy only grab the most recent one in the commit log?

**Comment by rocketnia** [comment]
It sounds like there should be a new commit. @akkartik, did you push it somewhere or just commit locally?

**Comment by SoniEx2** [comment]
If you add a second project commit at a later date, GAnarchy instances have a choice between moving to the new commit (and removing/excluding old forks) and/or sticking with the old one. This is intentional, and is meant to allow diverging forks to become diverging projects entirely over time.

**Comment by akkartik** [comment]
I like supporting the scenario of forks become diverging projects. But what about when the new commit is present 'upstream'? A project just wants to edit its name or description?

Does GAnarchy for some reason just never know where commits 'are hosted'? Does it just deal with commit trees?

**Comment by akkartik** [comment]
@rocketnia it turns out `git pull --rebase` just drops empty commits entirely 😂 🥇 Now recreated.

**Comment by SoniEx2** [comment]
There is no "upstream" - it's specifically designed to end the concept of "upstream".

Granted, in the case of something like this repo/project, the concept of "upstream" might not be so harmful. But I'd rather play it safe, and keep it out altogether.

(Besides, there's the whole thing where the web+ganarchy links link to what's essentially the commit hash. It's basically p2p with a server to help smooth things out.)

**Comment by SoniEx2** [comment]
I guess it's *possible* to do something with signed commits. I wouldn't know how to do it, tho.

**Comment by akkartik** [comment]
I'm still curious about how your instance works today for a linear commit log that has no branches:

```
o commit 1
o commit 2
o commit 3
o [Project] abc
o commit 4
o [Project] def
o commit 5
...newer commits...
```

Does the description `abc` apply to commits before it? After it? Both?

Other instances may choose differently, sure. But you have the opportunity to set the tone here.

**Comment by SoniEx2** [comment]
the description applies to the project. a project is a collection of repos with the given commit.

there can be overlap, so e.g., in some perhaps historical way, the description "abc" would apply to all of them, and so would "def".

in my instance, I'll generally prefer to keep the repos grouped based on the *latest* project commit they have, but in some cases I may group them based on an older project commit if I believe it'll be better for the users of the projects.

**Comment by akkartik** [comment]
Ahh, I understand now, thank you for answering my questions. Here's how my mental model evolved:

a) Tree of projects (the way GitHub shows them, with the original repo at the root and forks under it)
b) A single large tree of commits that gets added to from various repos in different places online.
c) (*Correct*) A bag of trees of commits, one tree for each repo hosted in a different place online, with no further relationship between trees (so far).

Hopefully I got that right..

**Comment by SoniEx2** [comment]
While it *does* have access to the full trees (per head/branch), it only shows the latest commit in that head/branch, with a link to the full repo so you can clone it yourself. Again, I don't really know how to make it do anything fancy, so it's really just a sorted list (it's sort-of sorted by activity).

**Comment by SoniEx2** [comment]
But I mean, yes, you *can* say it's that.

**Comment by SoniEx2** [comment]
update: https://ganarchy.github.io/
