### ISSUE TITLE
Topright becomes 'login' when trying to submit

### ISSUE THREAD

**Issue by tarvos21** [arclanguage/anarki#192]
Hi, I run anarki/apps/news on my Macbook, with Racket 8.0, I can create account and posts, however, when I try to submit post, the topright corner becomes 'login'. 

If I have logged in, I can submit successfully. But it's wierd, the topright is supposed to show usernames, I think.

Any suggestions how to fix this? Thanks!

<img width="1200" alt="截屏2021-03-05 08 41 00" src="https://user-images.githubusercontent.com/18745870/110050374-b88cdf00-7d8e-11eb-845d-238fbed076e6.png">

**Comment by akkartik** [comment]
I can reproduce this, and I also see the problem. Stay tuned..

**Comment by akkartik** [comment]
Try it now? My change is just a band-aid. You might see a few other places that have the same problem. Hopefully this commit shows how to clean them up.

**Comment by tarvos21** [comment]
@akkartik It's great for the submit page now, thanks!

**Comment by kennethrapp** [comment]
This is weird, because all of the subtemplates like minipage just end up calling the longpage template. There may be some arguments in the wrong order.

**Comment by akkartik** [comment]
minipage doesn't take a user, and it passes a nil user down to it's callees. Before, it just never showed anything in the top right. Now it misleads. So it might be worth looking at all calls of this family of functions and checking the code to see if argument defaults are sensible. Sometimes you have a user and it's better to pass it on. In other words it's useful to replace calls to minipage with something else. And so on.

**Comment by kennethrapp** [comment]
I see now. I just made a quick check and it looks like every function that calls minipage could get access to the user, so there's probably no reason it should ever be nil.  I can probably get this fixed by tomorrow.

**Comment by kennethrapp** [comment]
Currently login and submit are broken because somewhere user is being referenced before being defined, so a nil user is a problem somewhere. Still can't find it.

But everything did work when I was logged in so some progress was made.
