### ISSUE TITLE
Only admin can create new blog?

### ISSUE THREAD

**Issue by tarvos21** [arclanguage/anarki#193]
Hi, I load the blog.arc into news.arc. And it seems only admin account can create new blogs.

If a use is not admin, he just can not see the `new post` link when going to `/blog`.

Is it intended to act like this? Thanks!

**Comment by akkartik** [comment]
It seems possible. Blogs often have a single person writing posts. It's not clear what other users might be for. Maybe future features like comments?

My understanding is that blog.arc was never used in production anywhere. It was one of the example apps that Arc came with when it was released. But news.arc was the real example app. To my knowledge nobody has run with blog.arc and actually tried to build on it.
