### ISSUE TITLE
Mobile responsiveness?

### ISSUE THREAD

**Issue by tarvos21** [arclanguage/anarki#196]
Hacker News provides basic responsiveness on mobile/tablet, I know this is not only for the news applications, but is there any plan to improve the styles on mobile phones and tablets?

**Comment by akkartik** [comment]
Not to my knowledge, but anybody is welcome to make plans.

I'm probably stating the obvious, but changes to this repo aren't reflected in Hacker News the site.

**Comment by tarvos21** [comment]
OK, thanks!
