### ISSUE TITLE
readme is just a bit too cryptic

### ISSUE THREAD

**Issue by notottoman** [arclanguage/anarki#208]
"Install Racket then" then do what? it literally just says a buncha code and doesnt say anything or where to even put it or just anything about it, give me some information, something, anything! waaaaaaaaaaaay too cryptic for an idiot like me

**Comment by kennethrapp** [comment]
Those are commands you're supposed to run in a shell, one line at a time. I guess it could stand to be better explained.

**Comment by zck** [comment]
Updated a bit in 1bd0fe82c376fe3699028b9adcebdddb4547a1ec.
