### ISSUE TITLE
'for' doesn't terminate

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#22]
In the arc tutorial ( http://old.ycombinator.com/arc/tut.txt ) the for loop is expected to behave like this (and it does in arc-nu):

    arc> (for i 1 10 
           (pr i " "))
    1 2 3 4 5 6 7 8 9 10 nil

but in anarki it doesn't terminate:

    arc> (for i 1 10 
           (pr i " "))
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 user break
    context...:
    recur
    recur
    recur

If it is intended behavior, maybe it should be listed in the CHANGES file?

**Comment by akkartik** [comment]
Thanks for the report, and sorry about that. I knew it was incompatible with arc, but I didn't think through that it would manifest as non-termination. Thanks also for your change to the documentation. I've given you commit rights; can you submit your change?

**Comment by akkartik** [comment]
I added a command called `(incompatibilities)` at the repl and tried to list out the differences that I'm aware of. Can you pull it into your repo and see if it looks ok? Thanks.

**Comment by hjek** [comment]
Yay, thanks for letting me add to the docs! It appears that I don't have permission to push to the Anarki repository yet:

    remote: Permission to arclanguage/anarki.git denied to hjek.
    fatal: unable to access 'https://github.com/arclanguage/anarki.git/': The requested URL returned error: 403

**Comment by akkartik** [comment]
Ack, let me check.

**Comment by akkartik** [comment]
Hmm, it should work. It shows that you still have a pending invitation. Maybe you need to click on a link in the email or something?

**Comment by akkartik** [comment]
Oh, just a clarification: are you updating the commandline help or the reference?

**Comment by akkartik** [comment]
I think you might also need to update the url on your repo's `.git/config` from https to git. Use `git@github.com:arclanguage/anarki`. You might also need to [add an ssh key](https://help.github.com/articles/generating-ssh-keys).

**Comment by hjek** [comment]
Oh, I just overlooked the invitation email, I think it works now, but I won't push because I think your description is better. The rename of 'for' to 'up' is totally appropriate considering there's already a 'down', and it's really helpful with the 'incompatibilities' presented at the REPL.

**Comment by akkartik** [comment]
Submit anyway. I think the help doc for `for` is still a good place to highlight incompatibilities. Feel free to tweak or improve your text if you like.

**Comment by akkartik** [comment]
We can always polish things more after submitting. Not to mention we'll make sure pushing works for you :)

**Comment by hjek** [comment]
Yay, it worked! If I manage to get anything useful done, I'll add some modules (I'm trying to extend news.arc with a map, using Leaflet)
Also, there are some other things that look interesting (like blog.arc) but are lacking in documentation, but if I figure out how they work, I might add some brief instructions.

**Comment by akkartik** [comment]
Thanks! I've also added a pointer to the CHANGES file in the commandline
help for `for`.

I'd love to see any other ideas you have. Feel free to ask me any questions
you have about blog.arc, or anything else.
