### ISSUE TITLE
run-news killed

### ISSUE THREAD

**Issue by flamingtop** [arclanguage/anarki#23]
I set up anarki on ubuntu 14.04 32bit, behind nginx. It runs well most of the day, but the process got killed for no obvious reason. I've checked the wiki/forum and this doesn't seem a known issue. I'm not familiar with anarki debugging. I wonder if some one could shed some light on what might cause the following issue. I'm not sure if it's an anarki issue per se, it could be my nginx configuration or some other component. Just trying my luck here. Thanks in advance

```
./run-news 

.....

    recur
   zz
    g2534
    g1517
    handle-request-thread
    handle-request-thread
tcp-write: error writing
  system error: Broken pipe; errno=32
  context...:
   /usr/local/racket/collects/racket/private/map.rkt:26:19: loop
   /home/shawn/news.warmgogo.com/ac.scm:1477:0: ar-close
    handle-request-thread
tcp-write: error writing
  system error: Broken pipe; errno=32
  context...:
   /usr/local/racket/collects/racket/private/map.rkt:26:19: loop
   /home/shawn/news.warmgogo.com/ac.scm:1477:0: ar-close
    th1
./run-news: line 3:  7164 Killed                  ./arc lib/run-news.arc
```

**Comment by tvvocold** [comment]
Maybe it ran out of memory,try loop:
`while true; do ./run-news; sleep 5; done`

BTW,nice [site](news.warmgogo.com) with simple css!

Source: http://arclanguage.org/item?id=18900

**Comment by flamingtop** [comment]
I guess out of memory is quite possible since my server is a tiny 512M RAM virtual box.
I can use the while true trick to keep it running. Though I suppose when run-news is live, sleep 5 is blocked, yes?
Also I changed this line and I'm not sure if that's relevant

-  (and (only.> (requests/ip* ip) 250)
+  (and (only.> (requests/ip* ip) 1000)

**Comment by tvvocold** [comment]
@flamingtop 
I don't think so that line coz the problem.
BTW, i notice you had change a lot in news.warmgogo.com ,so can you push your (changed) code to github? (remeber to delete the emails or users' info)

**Comment by flamingtop** [comment]
@tvvocold 

It's here https://github.com/arclanguage/anarki/compare/master...flamingtop:news.warmgogo.com 
nothing sensitive.

**Comment by tvvocold** [comment]
@akkartik @shader

**Comment by flamingtop** [comment]
Added swap to my vbox, https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04
Hope this would solve the issue - if it's due to memory.

**Comment by tvvocold** [comment]
Yeah, i had this problem  in my openshift' gear , then i  fixed it by force stop and restart the app.

**Comment by akkartik** [comment]
Thanks for the answers @tvvocold! Your diagnosis was exactly what mine would have been. @flamingtop, don't worry the `sleep` won't affect the running of the server. Look at the arclanguage link @tvvocold mentioned above for details on why it's there.

I'm not sure adding swap will make this problem go completely away. The unfortunate fact is that the HN server's memory footprint gradually grows over time[1], using up whatever is available. If you add memory or swap it'll just take longer to run out. Back when I ran a service I always ran the server inside that `while` loop.

[1] Mostly this is because of the cache of stories and users which is lazily loaded as people access pages. You don't have many of them yet, so perhaps this won't be an issue for you for a while.

**Comment by flamingtop** [comment]
Thanks @akkartik, I'll use the while loop.

**Comment by shader** [comment]
Maybe we should consider adding some simple memory management to news.arc?

Kinda hackish, but we could add an intermediate cache table to check before loading from disk. After N stories have been loaded, rotate tables. Adds a small amount of overhead, but guarantees no more than 2*N items are ever loaded. Presumably user data etc. is not a problem.

Alternatively we could make a more complete system for lazy loading and background-persisting objects that supports timeout and size limits, or outsource via api to something like Redis which is actually meant for this.

**Comment by akkartik** [comment]
Hmm, so what we'd need is a data-structure equivalent of *defcache*. Like *defcache* meets *disktable*. Everytime its size exceeds n, find an element added longer than some time ago and delete it. Yes, this could work. @shader wanna work on it together? :)

**Comment by ShawnXu** [comment]
How about avoiding loading things to memory? At least provide an option? I suppose the majority vboxes will eventually use SSDs, that fast enough?

**Comment by akkartik** [comment]
(I should say that my old readwarp site didn't use any of news.arc but needed restarts every few days. But it was a more involved codebase. This would help give a better experience for small sites.)

**Comment by akkartik** [comment]
@ShawnXu: that's a very good point.

**Comment by akkartik** [comment]
When I think about big changes like a lazy-loading system or @ShawnXu's direct-to-disk what stops me is that this codebase doesn't get enough testing, and bugs I introduce often sit around festering for months before someone reports them :/ If we had a few people who would hammer on changes and use them with growing data sets (like real sites) but also not be mad if we accidentally lost data, that would be great. But those also seem like incompatible requirements :/

**Comment by flamingtop** [comment]
sorry used the wrong account, prev msg: stop anarki from loading things into memory or provide option to switch that off due to the trend that most hosting servers will run on SSDs eventually. (Shawn)

**Comment by akkartik** [comment]
:+1:

BTW, I'll add a note to the wiki for known bugs.

**Comment by hjek** [comment]
I'm gonna be doing some work on a real site using news.arc a lot with some growing data sets on a server with 256 MB RAM (raspberry pi).
I'll make sure to run the newest Anarki, especially now lazy loading might be implemented. I'll file any bugs I run into.

On Wed, 29 Apr 2015 10:09:13 -0700
Kartik Agaram <notifications@github.com> wrote:

> When I think about big changes like a lazy-loading system or @ShawnXu's direct-to-disk what stops me is that this codebase doesn't get enough testing, and bugs I introduce often sit around festering for months before someone reports them :/ If we had a few people who would hammer on changes and use them with growing data sets (like real sites) but also not be mad if we accidentally lost data, that would be great. But those also seem like incompatible requirements :/
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/arclanguage/anarki/issues/23#issuecomment-97506491


-- 
Pelle Hjek <hjek@mail.com>

**Comment by akkartik** [comment]
Awesome! That certainly provides motivation.

**Comment by akkartik** [comment]
Hmm, as I start planning the change I notice that unloading some items can worsen the HN dup detector. There might be other side effects as well.

**Comment by flamingtop** [comment]
@akkartik You mean there're multiple code points/components interfacing with what's in the memory?

**Comment by akkartik** [comment]
No, sorry I wasn't clear. I was referring to a much simpler feature, that notices you've submitted a duplicate url and turns it into an upvote for the existing submission. The way it works is that it checks for duplicates in only loaded items. If we start dropping items that are rarely loaded, we might permit more duplicates for them. Which might not be a big deal, it might even be useful.

For where objects get written to memory, look at `save-item` and `save-user` in `lib/news.arc`. Perhaps the first thing we should do is extract them and their helpers (up to the `item` and `profile` `deftem` definitions) into a separate file. Then we could write some unit tests around the interface before we try to swap in a new implementation.
