### ISSUE TITLE
POST requests time out

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#25]
I'm trying to send a file from the browser to the Arc server via a POST request. To test it, I am just sending from localhost to localhost. I have a simple HTML form sending the file to the server:

```
    <form  action="http://localhost:8080/helloworld" method="post" enctype="multipart/form-data">
            <input type="file" name="submission"></input>
            <input type="submit"></input>
    </form>
```

and I'm just printing the request from the Arc server:

```
(defop helloworld req (pr req))
(thread (asv))
```

With some files it fails with the browser just hanging and the console printing an error message:

```
srv thread took too long for ::1
```

The issue doesn't appear to be only about the size of the file, because this one file that's 50KB always fails, but this other file that's 116KB always succeeds. I notice that in `ac.scm` there's this variable called `upload-limit*`, but it appears to be set to ~30MB.

At one occasion the error message was slightly longer (maybe there's something useful about where it got stuck?):

```
    srv thread took too long for ::1
tcp-write: error writing
  system error: Broken pipe; errno=32
  context...:
   /home/pelle/arc/anarki/ac.scm:931:0: printwith
    map1
    pr
    prrn
    respond
    handle-request-thread
    handle-request-thread
tcp-write: error writing
  system error: Broken pipe; errno=32
  context...:
   /usr/share/racket/collects/racket/private/map.rkt:26:19: loop
   /home/pelle/arc/anarki/ac.scm:1485:0: ar-close
    handle-request-thread
tcp-write: error writing
  system error: Broken pipe; errno=32
  context...:
   /usr/share/racket/collects/racket/private/map.rkt:26:19: loop
   /home/pelle/arc/anarki/ac.scm:1485:0: ar-close
    th1
```

There's [some talk about file uploads in Arc forum](http://arclanguage.org/item?id=18947), but it's also concerning an interesting mix of Arc versions.

I'm just trying to get this working on vanilla Anarki. I also tried running the above code in Rainbow, but it doesn't even get the content of the file sent in the POST request, `(((req 'args) 'submission) 'content)`.

I am not sure if I am doing something wrong here, or if there's something broken. Are there any good ideas for workarounds, if it is something that can't be fixed? (Using PHP for file uploads is not the answer I'm looking for here :-)

As a side note, of course I am planning to share these optional extensions to HackerNews when they're working well enough. Is it preferred to add these extensions to the `lib` folder or the `extras`?

**Comment by akkartik** [comment]
Thanks for looking into this! I've never played with Rainbow but I'm not surprised it doesn't work considering Arc 3.1 didn't really have much attention devoted to file upload in the first place. Even my initial stab is quite basic. Can you share the files you're testing with? I'll try to reproduce on my end.

**Comment by hjek** [comment]
(For the record; shared files via email, but any files above 100KB will usually reproduce the error anyway) The issue seems to be there in plain Arc 3.1 run with `racket -I mzscheme -f as.scm` as well. But at least Anarki will get the actual content of the file sent in the POST request (if the file is small enough), as opposed to Rainbow Arc and plain Arc 3.1 in MZScheme. Will investigate further, and maybe try implementing a reasonable POST request handler using Racket.

**Comment by akkartik** [comment]
Thanks!

**Comment by hjek** [comment]
It looks to me like `scan-past` is a major bottle neck. If `scan-past` is replaced with a dummy function, just outputting `(range 1 1000)`,  the multipart POST requests take almost no time.

I've faffed around with it a bit, and I've come up with an alternative version that depends on more **Racket** functions, but is (hopefully) faster.

This is what the new `scan-past` looks like,
```
(def fast-scan-past (pat in)
  (let in ($.port->bytes in)
    ($.bytes->list (car ($.regexp-split pat in)))))
```

It appears to behave the same within the repl. However, when submitting a POST request with `lib/form-tests.arc`, it times out.

**Comment by hjek** [comment]
It looks like nothing (in this repository) depends on this multipart POST request functionality, so I assume I can drastically change things without causing any breakage.

**Comment by akkartik** [comment]
Sounds good. There's a unit test or two that checks it. That may be worth keeping in spirit.

**Comment by akkartik** [comment]
Can you share how you test `scan-past` at the REPL? Let me try to play with it.

**Comment by akkartik** [comment]
One thing I had to do to get your version working is add `port->bytes` to `ac.scm`. Then I see the timeout you see. Adding prints (using `ero`) it looks like `port->bytes` doesn't return before the deadline.

Reading [the docs for `port->bytes`](https://docs.racket-lang.org/reference/port-lib.html?q=port-%3Ebytes#%28def._%28%28lib._racket%2Fport..rkt%29._port-~3ebytes%29%29), it looks like it tries to read the entire contents of the port. That isn't what we want from `scan-past`. We want it to stop reading at a multipart boundary, so that subsequent reads will return the next boundary.

I don't know if this is the cause of the timeout. That still seems weird. But perhaps it's not worth trying to debug.

**Comment by hjek** [comment]
`ero` is nice, didn't know about that one (which was a bit of a problem, given that `pr` is used for the web app output). I'll probably have a look at how [**formidable**](https://github.com/felixge/node-formidable) does its parsing.

**Comment by hjek** [comment]
Yes, I'd put `port->bytes` in `ac.scm`. I'll push the code if i get any speed improvements.

**Comment by hjek** [comment]
I'd totally misunderstood what `scan-past` was doing. The whole point of it is that it *doesn't* read all bytes in the port, but only until the boundary. So `port->bytes` is useless.

Anyway, the current version looks very frugal. Don't know why it's so slow! But [Boyer-Moore](https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore_string_search_algorithm) could be faster anyway.

**Arc**'s `time` is great for profiling.

**Comment by hjek** [comment]
With my first messy attempt at the simplified Boyer-Moore-Horspool algorithm, it's noticeably faster. (It only has the **bad characters rule**, not the **good suffix rule**.)

I hope I can get **Arc** to deal with 5 mb uploads, at least. Perhaps it'll be necessary with [Raita algorithm](https://en.wikipedia.org/wiki/Raita_algorithm).

**Comment by hjek** [comment]
I've changed the POST request parsing to read the whole request before parsing.

It seems a lot faster but it's also not completely correct yet, and it is failing a test.

I think I'll just push it now, but it's work-in-progress.

**Comment by hjek** [comment]
Oh no, it's actually a lot slower.

**Comment by hjek** [comment]
Made a basic file upload app in Racket. It is [a lot faster](https://notabug.org/hjek/share), and less than 100 lines, so not too complicated.
