### ISSUE TITLE
Error when running ./arc

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#28]
When I `$ ./arc` per the README instruction I get this error: 
`$ ./arc: line 76: rlwrap: command not found`

I am running OS X and I installed racket via homebrew if that's relevant.

**Comment by Kinnardian** [comment]
`$ brew install rlwrap` seems to get me past this error. But now I get a new one.

**Comment by akkartik** [comment]
Thanks. What's the new one?

**Comment by Kinnardian** [comment]
https://github.com/arclanguage/anarki/issues/29

**Comment by Kinnardian** [comment]
In any case, this worked in its own directory: http://arclanguage.org/item?id=19283

**Comment by zck** [comment]
As a side note, you can run arc without `rlwrap` by [passing the `-n` argument](https://github.com/arclanguage/anarki/blob/master/arc#L10) to it:

    ./arc -n

**Comment by hjek** [comment]
To give a useful error message, we can add something like this to the `arc` shell script somewhere after `RLWRAP` is defined:
```
if $RLWRAP && [ ! `which rlwrap` ]
  then if [ `uname` = "Darwin" ]
    then echo "Please run: \"brew install rlwrap\""
    else echo "Please install rlwrap"
    fi
    echo "or run arc without rlwrap: \"./arc -n\""
fi
```
