### ISSUE TITLE
Error when running ./arc.sh

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#29]
I get this error when I run `$ ./arc.sh`:
```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
./arc.sh: line 12: mzscheme: command not found
./arc.sh: line 24: mzscheme: command not found
./arc.sh: line 40: [: =: unary operator expected
rlwrap: error: Cannot execute mzscheme: No such file or director
```

**Comment by akkartik** [comment]
That's a very strange error. Maybe your copy is really old? There should be no mention of mzscheme in arc.sh; it should only call racket.

**Comment by akkartik** [comment]
Can I send you some corrections to try out for the `rlwrap` and `readlink` issues?  I don't have access to a Mac.

**Comment by Kinnardian** [comment]
Certainly

**Comment by Kinnardian** [comment]
In any case this worked in its own directory: http://arclanguage.org/item?id=19283

**Comment by akkartik** [comment]
Great. I'm curious, were you running anarki before?

**Comment by Kinnardian** [comment]
Nope, I've never successfully run anarki or arc in general outside of those instructions.

**Comment by akkartik** [comment]
I understand now. You're trying the stable branch, which still uses mzscheme. Ok, so that explains the first issue. I'll update the stable branch to run with the latest version of racket as well.

**Comment by akkartik** [comment]
But I thought you said you followed the directions in the Readme? I think I still don't understand.

**Comment by Kinnardian** [comment]
I was on master at first, then I switched to stable per the instructions here: http://arclanguage.github.io/

**Comment by Kinnardian** [comment]
On master I get: 
```
$ ./arc
boot.scm:1:9: collection not found
  for module path: mzscheme
  collection: "mzscheme"
  in collection directories:
   /Users/Kinnard/Library/Racket/6.3/collects
   /usr/local/Cellar/racket/6.3/share/racket/collects
   /usr/local/Cellar/racket/6.3/share/racket/pkgs/racket-lib
  context...:
   show-collection-err
   standard-module-name-resolver
```

On stable I get:

```
$ ./arc
-bash: ./arc: No such file or directory
$ ./arc.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]
./arc.sh: line 12: mzscheme: command not found
./arc.sh: line 24: mzscheme: command not found
./arc.sh: line 40: [: =: unary operator expected
rlwrap: error: Cannot execute mzscheme: No such file or directory
```

**Comment by akkartik** [comment]
Thanks; will try the directions later today. I wonder if Racket has deleted the mzscheme language..

**Comment by hjek** [comment]
Have you installed **Minimal Racket** or normal **Racket** ( [**OS X x86 64** version here](https://mirror.racket-lang.org/installers/6.4/racket-6.4-x86_64-macosx.dmg) )? I don't think **mzscheme** is included in the minimal distribution.

**Comment by Kinnardian** [comment]
Yes that's correct, I've got **Minimal Racket** from my homebrew installation.
```
$ brew info racket
racket: stable 6.3 (bottled)
Modern programming language in the Lisp/Scheme family
http://racket-lang.org/
/usr/local/Cellar/racket/6.3 (1,724 files, 21.5M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/racket.rb
==> Caveats
This is a minimal Racket distribution.
If you want to use the DrRacket IDE, you may run
  raco pkg install --auto drracket
```

**Comment by Kinnardian** [comment]
```
$ raco pkg install --auto drracket
$ ./arc.sh
``` 
Has me up and running . . . on master . . .

**Comment by akkartik** [comment]
Ah, great. Thanks for that tip @hjek!

@Kinnardian: feel free to send a pull request improving the Readme :) Thanks in advance.

**Comment by Kinnardian** [comment]
Thanks @hjek! Sure @akkartik.

Now I'm wondering how to actually run drracket . . .

**Comment by hjek** [comment]
**DrRacket** is mainly for **Racket** and a few other languages, and it's not terribly useful for editing **arc**. There is syntax highlighting for [vim](https://github.com/vim-scripts/arc.vim) and [emacs](https://sites.google.com/site/arclanguagewiki/getting-started/installing-emacs) though. I think the easiest thing is to keep an arc REPL open and run `(load "whichever-file-youre-editing.arc")` whenever you want to reload changes.

**Comment by Kinnardian** [comment]
So I think I originally missed the "To run, install Racket from http://racket-lang.org, then:" in the readme . . . 

Would adding
`$ brew install racket`
`$ raco pkg install --auto drracket`
be too prescriptive? I know people have their preferred package managers and installation methodologies.

**Comment by akkartik** [comment]
It's not so much preferred package managers as just providing some decent
default for all OSs.

Aside from that, there's a second reason I prefer to just point to
racket-lang.org so people can follow the install directions there -- you
end up with a more up-to-date version of Racket. Different OSs vary widely
in how stale a version they distribute, which makes questions harder to
answer. Mac OS has been a prime culprit in this area in the past. You're
just going to save a lot of trouble if you sidestep brew and install Racket
to your own Desktop or someplace like that.

The racket instructions are *very* easy to follow. Let me know if they
cause you any trouble.

**Comment by hjek** [comment]
The `brew install racket` instructions are useful only on **OS X** and when **racket** isn't yet installed, so maybe @Kinnardian could consider adding it to the `arc` shell script as an error message for that particular case.

The `arc` shell script already contains some **brew** related error messages, like `echo 'Please do "brew install coreutils".'` so I would suggest putting it there.

**Comment by akkartik** [comment]
That'd be fine. I haven't had Mac in a while so I have no idea if there's
any bitrot in that script on Macs. Maybe I'll similarly add Linux support
as well.

**Comment by Kinnardian** [comment]
The homebrew package is pretty up to date(last commit 5 hours ago): https://github.com/Homebrew/homebrew/blob/master/Library/Formula/racket.rb

But not quite perfect: https://github.com/Homebrew/homebrew/issues/49699

**Comment by akkartik** [comment]
Ok, I'm convinced. Feel free to make a draft and I'll give you commit rights. We can always iterate on it later.

**Comment by hjek** [comment]
We can put it in an error in `arc` launch script somehwere:
```
if [ `uname` = "Darwin" ] && [ ! `which racket` ]; then echo "\
  Please do:
  \"brew install racket\"
  \"raco pkg install --auto drracket\"";
  exit 1
fi
```

**Comment by akkartik** [comment]
@Kinnardian has already submitted a change :)
https://github.com/arclanguage/anarki/pull/34

**Comment by hjek** [comment]
Nice!
