### ISSUE TITLE
Future of Arc

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#30]
Are there any big plans for the future of arc? Future releases? Future features?

**Comment by akkartik** [comment]
You mean anarki :) Totally different from 'official' Arc.

No, no plans. I like to answer questions and accept suggestions/pull requests from anyone. If you make plans we're amenable to them :) I'll give you commit privileges after your first commit.

**Comment by Kinnardian** [comment]
Anarki seems like the only part of official arc that's still alive, that's why I posted here.

**Comment by akkartik** [comment]
Glad you did!

**Comment by Kinnardian** [comment]
I'm down to dig in if at least two other people are.

**Comment by akkartik** [comment]
Happy to join you. Let's start with just learning what's there, and when ideas strike it'll be easier to move on them than with any other language.

**Comment by akkartik** [comment]
For example, zck recently made a slick unit test harness for Arc. So I know he still keeps his hand in.

**Comment by zck** [comment]
I was semi-summoned here (and thanks for the plug), so yeah, I do kind of keep my hand in. The more I hear about people using arc (especially unit-test.arc), the more likely I am to do stuff in it.
