### ISSUE TITLE
Unbundling Libraries from anarki

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#32]
There are several libraries that ship with arc: https://github.com/arclanguage/anarki/blob/master/libs.arc
What's the rational for bundling them?

**Comment by akkartik** [comment]
I don't know that we've ever explicitly discussed the matter. Do you mean
loading them by default in `libs.arc`, or including them at all in the
repo? I can think of a few reasons, though others might have a different
set.

a) For a long time anarki was set up to be a public wiki-like experiment
that anybody could commit to. So one reason stuff entered here is probably
that it was easiest: you didn't have to create a new repo and then hope
others found it. Any code you wrote became more easily discoverable. (We
stopped being a wiki when github stopped supporting publicly modifiable
repos, but we still give commit rights to anyone who asks. Would you like
the keys? :) )

b) We tend to have a more liberal aesthetic for modularity in this
community, preferring a single global namespace unless there's a strong
reason for namespacing in a specific situation. So we prefer a "batteries
included" style of software sharing that doesn't require a lot of
decentralized foraging for libraries.

c) If libraries are included we try to make them work well together. At
least, if you report a bug anybody can take a stab at fixing it without
worrying about permissions, etc.

d) Once you include code in a repo, not loading it by default is just a
recipe for accelerated bitrot.

**Comment by Kinnardian** [comment]
Would this be badly handled by a package manager?

**Comment by akkartik** [comment]
Yeah, a package manager would work great, if you want to build one :) I'm
not sure the scale of the community merits it just yet..

**Comment by hjek** [comment]
@Kinnardian if you don't need the extra libraries, there's [plain arc](www.arclanguage.org/arc3.1.tar), and run it with `racket -f as.scm`

**Anarki** loads a few more libraries at start up, such as `lib/news.arc`, and I think some of the reasoning for that is that you just have to type `(nsv)` in the REPL to run **News**.

Most of the libraries in `./libs.arc` are fairly essential. Consider that unbundling `./lib/help.arc` would mean that users would have to learn and use a new package manager to activate the `help` function.

**Comment by Kinnardian** [comment]
Are there any you guys would say are definitely non-essential? The News App seems the most obvious to me.

**Comment by akkartik** [comment]
Yes, the news app is perhaps the single largest app and most likely to
deserve first-class status. However, pretty much everyone who came to arc
came to try it out, so there's value in keeping it bundled and eliminating
one step from our install instructions.

**Comment by Kinnardian** [comment]
Haha, that's why I came. Now I'm stuck! #venusflytrap . . .

**Comment by akkartik** [comment]
:smiling_imp:

**Comment by Kinnardian** [comment]
I went through and tried to figure out which `/lib/` files were "nonessential"


name | description | file | essential/nonessential | 
---- | --------- |  --- |  --------------------- | 
app? | general application server |  anarki/lib/app.arc |  nonessential | 
arcscript? |  Utilities? |  anarki/lib/arcscript.arc |  ? | 
avl-trees |  AVL Tree Library |  anarki/lib/avl-tree.arc |  nonessential? | 
arc-binary? |  binary manipulation library? |  anarki/lib/binary.arc |  nonessential | 
arcblog? |  Simple Blog |  anarki/lib/blog.arc |  nonessential | 
arc-code-analysis? |  code analysis library |  anarki/lib/code.arc |  nonessential | 
arc-crypto? |  arc crypto-primitives library |  anarki/lib/crypto.arc |  nonessential | 
date |  date parser |  anarki/lib/date.arc |  essential | 
declare? |  ? |  anarki/lib/declare.arc |  ? | 
defpat |  pattern matching library |  anarki/lib/defpat.arc |  essential | 
dispatch? |  web toolkit? |  anarki/lib/dispatch.arc |  nonessential | 
dotted? |  dotted list processing | anarki/lib/dotted.arc |  essential | 
files? |  filesystem utility |  anarki/lib/files.arc |  essential? | 
fleetdb |  fleetDB library |  anarki/lib/fleetdb.arc |  nonessential | 
formtests |  html form utility |  anarki/lib/form-tests.arc |  nonessential | 
help |  help |  anarki/lib/help.arc |  essential | 
arc-html |  html utility library |  anarki/lib/html.arc |  nonessential | 
arc-http |  arc implementation of http |  anarki/lib/http.arc |  nonessential | 
arc-irc |  arc irc server |  anarki/lib/irc.arc |  nonessential | 
arc-json |  json parser |  anarki/lib/json.arc |  essential? | 
lang |  Call other languages(Perl and Python) from Arc |  anarki/lib/lang.arc |  nonessential | 
lru-cache |  augment a function with a cache of its most recent calls |  anarki/lib/lru-cache.arc |  nonessential | 
math |  math library |  anarki/lib/math.arc |  essential | 
arcnews |  Hackernews style application |  anarki/lib/news.arc | Staying | 
ns |  Utilities for managing Racket modules and namespaces |  anarki/lib/ns.arc |  essential | 
ppr |  pretty-print |  anarki/lib/ppr.arc |  essential? | 
prompt |  Prompt: Web-based programming application |  anarki/lib/prompt.arc |  nonessential | 
queue |  queue utility |  anarki/lib/queue.arc |  nonessential | 
rainbow-test? |  test-runner |  anarki/lib/rainbow-test.arc |  nonessential | 
re |  regex utility |  anarki/lib/re.arc |  essential? | 
require |  module loader? |  anarki/lib/require.arc |  essential | 
scheme? |  ? |  anarki/lib/scheme.arc |  ? | 
skipshite |  Skip whitespaces |  anarki/lib/skipwhite.arc |  nonessential | 
sml |  S-Expression Meta Language for XML |  anarki/lib/sml.arc |  nonessential | 
splicable-list |  Splicable List |  anarki/lib/spliceable-list.arc |  essential | 
http-server |  http server |  anarki/lib/srv.arc |  nonessential | 
statistics |  statistics and matricies library |  anarki/lib/statistics.arc |  nonessential | 
lazy-streams |  lazy streams using either lazy-cons or lazy-gen |  anarki/lib/streams.arc |  nonessential | 
strings |  string utility library |  anarki/lib/strings.arc |  essential | 
table-rw |  able reader / writer |  anarki/lib/table-rw.arc |  nonessential | 
tem-report |  ? |  anarki/lib/tem-report.arc3 |  nonessential? | 
tem? |  arc template library |  anarki/lib/tem.arc |  essential?
template? |  turn adjacent characters into a string |  anarki/lib/template.arc |  nonessential | 
text |  drainf and pump |  anarki/lib/text.arc |  essential? | 
trace |  function & macro tracing |  anarki/lib/trace.arc |  nonessential | 
tree |  different ways to navigate trees |  anarki/lib/tree.arc |  nonessential | 
util |  A collection of useful miscellanea |  anarki/lib/util.arc |  nonessential | 
arc-web? |  web utility library? |  anarki/lib/web.arc |  nonessential | 
wills |  Simplified interface to plt scheme's will executors |  anarki/lib/wills.arc |  nonessential |

**Comment by akkartik** [comment]
Wow, that's very thorough. What should we do with the nonessential libraries, to your thinking?

**Comment by Kinnardian** [comment]
I have an idea . . . but first I'm wondering if my designations are "correct" or not

**Comment by akkartik** [comment]
You know, most of that I don't use myself. blog.arc and app.arc are part of
the original version (app.arc is required by news.arc), tree.arc and
tem.arc (with its associated tem-report.* results) are part of the language
that I chose to pull out into their own libraries. utils.arc contains a
bunch of stuff, some likely very useful but will take effort to tease out.

More info on some of these:

tem.arc: https://arclanguage.github.io/ref/template.html
web.arc is an alternative to srv.arc: http://arclanguage.org/item?id=11337
scheme.arc: https://awwx.ws/scheme0
rainbow-test.arc: unit tests from the rainbow project. We run them from
old-tests.arc, but I admit I haven't run the old tests in a while. We can
probably drop it and everything it needs.

The rest, like I said I don't know. They were often added by people who
might still be using them, but if we delete it and they complain then we'll
know :)

**Comment by Kinnardian** [comment]
The [forum post](http://arclanguage.org/item?id=11337) says web.arc was created by Paul Capron? But in [web.arc](https://github.com/arclanguage/anarki/blob/master/lib/web.arc) it says it was created by Mark Huetsch and Brian J Rubinton?

**Comment by Kinnardian** [comment]
So dispatch which is a server library has been removed: https://github.com/arclanguage/anarki/commit/1752dff9f1656ffd4c1ce1409118f8478db4fbd4
I'm working on it here: https://github.com/Kinnardian/dispatch

**Comment by akkartik** [comment]
Put Paul Capron's name first in the credits, since he started it all:
http://arclanguage.org/item?id=11337

**Comment by Kinnardian** [comment]
Haha, these names have changed a lot. Done.
