### ISSUE TITLE
lib/blog.arc not working

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#35]
What is the blog supposed to look like? Is it in production anywhere? I'm guessing it's not supposed to look like what I'm seeing.

And I get this error when I visit http://localhost:8080/newpost:
```
_reassemble-args: undefined;
 cannot reference undefined identifier
  context...:
    g20213
    handle-request-thread
    handle-request-thread
```

**Comment by akkartik** [comment]
Ack, looks like that's my fault from 2 years ago:
https://github.com/arclanguage/anarki/commit/05c3c3051a416f60b70d347b31f61d6a1520d890.
I'm fixing it now.

It's actually needed by the HN login system as well in app.arc, so it's
surprising no breakage manifested there.

**Comment by akkartik** [comment]
I've brought back `reassemble-args`:
https://github.com/arclanguage/anarki/commit/e05b061180e6cf2db75fc4f1b5f7be7ab42902ea.
Could you see how things look now? I can't run it yet because -- *heh*
-- I'm now on mac and the `arc` script dies with this error:

```
$ ./arc
which: invalid option -- s
/usr/local/bin/greadlink
which: invalid option -- s
```

Thanks for this bug! I've given you credit in my commit.

**Comment by Kinnardian** [comment]
Hmmm, it appears there are multiple issues. I'm getting other error messages. Not sure how to triage.

The error you're getting is  because of the double dash?

**Comment by akkartik** [comment]
No, I think it's the `-s` option passed to `which`. Does that work for you?
What does `-s` do, can you figure out?

**Comment by akkartik** [comment]
I just upgraded the (absolutely *prehistoric*) default bash to 4.3,
but still get the same error.

Looks like `which -s` means "silent", though I don't know in what
version of what shell:
http://www.linuxforums.org/forum/programming-scripting/70522-how-check-command-exist.html.

I'll throw in a redirect to `/dev/null`.

**Comment by hjek** [comment]
On OS X `-s` is [silent](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/which.1.html)
> -s      No output, just return 0 if any of the executables are found, or 1 if none are found.

But on GNU/Linux it fails:
```
$ which -s which
Illegal option -s
Usage: /usr/bin/which [-a] args
```

**Comment by akkartik** [comment]
Ok, so a Linux vs BSD thing. Why has it stopped working even on OS X, I
wonder. I'm on El Capitan.

These changes now work for me:
https://github.com/arclanguage/anarki/commit/07832f9c537c79ecd36bb445f9e8055a2658c1b8.
Now I'm going to clean it up and add analogous checks for Linux.

**Comment by akkartik** [comment]
I've made a few more changes to the script, to improve the flow of the
logic and add error messages for Linux like the ones we have for Darwin.
Comments most welcome.

**Comment by akkartik** [comment]
Ok, so back to the original issue: does blog.arc work for you now, or do
you see a new error?

**Comment by Kinnardian** [comment]
Sorry about the delay #eastcoast. `which -s` was working fine for me on OS X Yosemite. Is it a better practice to redirect the output? No it's not working: https://github.com/arclanguage/anarki/issues/37#issuecomment-191836800

**Comment by akkartik** [comment]
Ok, let's continue there. I'll close this issue.
