### ISSUE TITLE
Unable to create blog user

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#37]
When attempting to a user from, upon pressing signup, the app navigates to http://localhost:8080/y and gives the following error in the arc REPL:

```
_ranked-stories*: undefined;
 cannot reference undefined identifier
  context...:
    recur
Type: unknown type #<path:/var/folders/95/9ty0c4jd2x1_vv_t3dwndsxh0000gn/T/shash.14570218371457021837209>
  context...:
   /Users/Kinnard/Desktop/anarki/ac.scm:1002:0: ar-coerce
   /Users/Kinnard/Desktop/anarki/ac.scm:752:8: +
    shash
    shash
    set-pw
    set-pw
    create-acct
    signup-handler
    respond
    handle-request-thread
    handle-request-thread
```
I'm guessing this is related to https://github.com/arclanguage/anarki/issues/36

**Comment by akkartik** [comment]
Yes, I mentioned it there. Are you on OS X as well?

**Comment by Kinnardian** [comment]
Yes

**Comment by akkartik** [comment]
I think I need to fix this issue even if it won't entirely fix #36. Trouble
is, it looks like we need to do different things for Windows and Mac OS..
Ah, I think I need to use this:
https://docs.racket-lang.org/reference/runtime.html. Will fix today.

**Comment by hjek** [comment]
I tried running **News** on Windows Vista some time ago, and couldn't get it working in either **anarki** or **arc 3.1**. I was under the impression that to run **News** on Windows, you might need **Cygwin** or something. (If it's intended to be working for Windows, I'll report some more issues.)

**News** has some unixisms; for example at line 169 in `lib/news.arc`:

`(system (+ "rm " storydir* "*.tmp"))`

**Comment by akkartik** [comment]
Yes, I think it requires cygwin. But I don't know if highCs was on cygwin..

**Comment by hjek** [comment]
If we assume people on **Windows** use **Cygwin**, I think we should at least link to it somewhere in the documentation, if not briefly explain how to run **anarki** using **cygwin**.

I might try it out on **ReactOS**.

**Comment by akkartik** [comment]
I've never tried it on Windows, so I have no idea :/ Cygwin is just a
guess. But yes, as people try it on new OS's, I'd love to expand directions
for them.

**Comment by Kinnardian** [comment]
I don't quite understand what happened here, and I still get a 
```
_ranked-stories*: undefined;
 cannot reference an identifier before its definition
  in module: "/Users/Kinnard/Desktop/anarki/ac.scm"
  context...:
    gc12832
    gc12832
    cache
    newspage
    g12806
    handle-request-thread
    handle-request-thread

```
error when I visit http://localhost:8080/ after an `(asv)`

**Comment by akkartik** [comment]
That is ugly but harmless and unrelated to this bug. What happens is that HN spawns a background thread to try to recompute top stories: https://github.com/arclanguage/anarki/blob/5ba7813b33/lib/news.arc#L333. However, when you start HN for the first time you often have no stories. A real website would never see this error.

Hold on, let me fix this so the error doesn't happen.

**Comment by Kinnardian** [comment]
I suspected that . . . . but `news.arc` isn't being run . . .  just `app.arc`

**Comment by akkartik** [comment]
Ah, there's one correction to my previous comment: it happens when you load
lib/news.arc (as we do by default) but then load `(asv)` rather than
news.arc's `(nsv)`. If you want to run some site other than news.arc, then
delete it from libs.arc.

BTW, this has nothing to do with the server itself. You'll see the error if
you start `(asv)` and just wait a couple of minutes without visiting the
frontpage.

**Comment by akkartik** [comment]
(Even though you don't run `nsv`, we're still loading lib/news.arc, which
kicks off the thread to periodically run `rerank-random`.)

**Comment by akkartik** [comment]
I'm digging even deeper down the rabbit hole. If the error doesn't require
a page load to happen, and if the background thread to run `rerank-stories`
always runs, why does the error not happen until we run `(asv)`? Answer:
`defbg` doesn't actually spawn a new thread, it just adds to a todo list of
threads to spawn. Threads are spawned inside `serve`, which is called by
`asv`: https://github.com/arclanguage/anarki/blob/5ba7813b33/lib/srv.arc#L12
.

Ok, *now* I understand :)

**Comment by Kinnardian** [comment]
Well, this everything-in-the-global-scope thing sure can be creepy . . . and it seems to invoke a lot of sleuthing . . . like ghost-hunting . . .
