### ISSUE TITLE
/lib/news.arc and arc-language forum

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#38]
Is the code in [/lib/news.arc](https://github.com/arclanguage/anarki/blob/master/lib/news.arc) up to date with the what runs at [arclanguage.org/forum](http://arclanguage.org/forum)? If not what important or meaningful differences are there?

**Comment by akkartik** [comment]
We don't know. The last public release of the HN codebase was back in 2009.
Though I suspect Arc Forum hasn't changed much even if HN has.

**Comment by akkartik** [comment]
Might be a better idea to post such questions on the Forum, since more people go there. I check both, but others may not.

**Comment by Kinnardian** [comment]
Done: http://arclanguage.org/item?id=19464
