### ISSUE TITLE
Access argv in arc?

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#39]
Don't know if this is the right place to ask this sort of question but: How do you access the `argv` type object in arc?

**Comment by akkartik** [comment]
Just use the variable `argv`! For example, try creating a file called `x.arc` containing just this one line:

```
(write argv)
```

Now call it thus:

```shell
$ ./arc x.arc a b c
```

Result:

```
("x.arc" "a" "b" "c")
```

**Comment by Kinnardian** [comment]
Ah, didn't occur to me to just try it . . . Thank you.
