### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by shader** [arclanguage/anarki#41]
I know I made an OpenShift container for Arc a few years ago. Has anyone since done the same on Docker?

If so, we should include a reference as it might help for system-agnostic setup. Just "docker run arc"
If not I can volunteer to make one.

**Comment by fauria** [comment]
Hi,

I just published a Docker image for Anarki: [https://github.com/fauria/docker-hn](https://github.com/fauria/docker-hn)

For more information, see this [discussion on Arc Forum](http://arclanguage.org/item?id=20006).

Feel free to send any issues or suggestions. 

Regards.
