### ISSUE TITLE
Format of POST request arguments in web.arc

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#44]
@huetsch & @brianru  What's the correct format of the `POST` request `args` for `post-url` in `web.arc`
```
(def post-url (url args)
  (cdr (mkreq url args "POST")))
```

```
(def build-query (querystr querylist)
  (string querystr
          (and (nonblank querystr)
               querylist
               '&)
          (to-query-str querylist)))

(def to-query-str (querylist)
  (if querylist
    (joinstr (map [joinstr _ "="]
                  (map (fn ((k v))
                         (list k urlencode.v))
                       (pair:map [coerce _ 'string] querylist)))
             "&")))
```
https://github.com/arclanguage/anarki/blob/master/lib/web.arc

**Comment by akkartik** [comment]
@Kinnardian I gather you figured this out. Can you post the answer and close?

**Comment by Kinnardian** [comment]
`(post-url "url" (list 'arg1 arg1 'arg2 arg2 'arg3 arg3))` is working for me.

For anyone looking [`web.arc`](https://github.com/arclanguage/anarki/blob/master/lib/web.arc) has moved to [`client.arc`](https://github.com/arclanguage/anarki/blob/master/lib/client.arc)

`client.arc`'s "documentation" has been been updated:
https://github.com/arclanguage/anarki/commit/6a285a8239f4da11a407ee93236a15c34b4d3c33
