### ISSUE TITLE
Accessing Current Directory

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#47]
The `files.arc` lib provides a `pwd` command. But how does it access the `current-directory`?
```
(def pwd ()
  " Returns the current directory. "
  ($ (path->string (current-directory))))
```
https://github.com/arclanguage/anarki/blob/master/lib/files.arc#L31

```
arc> current-directory
_current-directory: undefined;
 cannot reference an identifier before its definition
  in module: "/Users/Kinnard/Desktop/anarki/ac.scm"
  context...:
   /Users/Kinnard/Desktop/anarki/ac.scm:1251:4
```

**Comment by Kinnardian** [comment]
Also, what's `($ )`? That doesn't appear in the documentation anywhere or at least I haven't been able to find it.

**Comment by shader** [comment]
The $ macro is a special addition to anarki for escaping into racket.

**Comment by Kinnardian** [comment]
Ah, that sounds important. Is it documented anywhere? I bet it stands for scheme, right? Was this pg's work? It goes right up against his axiomatic philosophy?

**Comment by akkartik** [comment]
Yeah, the $ is an anarki invention to escape down to the underlying Racket.
If you try `($.current-directory)` that should work.

I'll add something to the online help.

**Comment by Kinnardian** [comment]
Is there anyway to do `($.current-directory)` in pure arc?

**Comment by akkartik** [comment]
Nope, which is why `$` exists. It's a pragmatic decision to not wait to
bootstrap everything from axiomatic first principles.

**Comment by shader** [comment]
Almost by definition not. "current-directory" is a function that is
ultimately provided by the operating system, and so must involve lower
level non-arc code. Until arc is self-hosted to the extent that it can
invoke an FFI directly, that is.

An alternative might be using `(system "pwd")` to run pwd as a shell
command and then parsing the resulting string...

**Comment by zck** [comment]
> An alternative might be using `(system "pwd")` to run pwd as a shell command and then parsing the resulting string...

Of course, this is non-portable, so it, too, is less than ideal.

**Comment by Kinnardian** [comment]
I wonder how racket does it.
