### ISSUE TITLE
Reading in files as strings

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#49]
It's not clear to me from the [I/O documentation](https://arclanguage.github.io/ref/io.html) how to read files in as strings. As yet I'm working with 

```
(each f (dir ($ (path->string (current-directory))))
    (unless (dir-exists f) (= (files f) (readfile f))))
```
But that throws an error when attempting to read in non-lisp files. My guess is that that's because readfile is specifically for lisp files.

readc and readb don't seem to be intended for reading in files and both throw errors.

What's a good way to read in an arbitrary type of file?

**Comment by akkartik** [comment]
`readc` and `readb` read from stdin, but you can redirect stdin using
`w/stdin`. There's even a more high-level helper called `fromfile` so you
can do this:

```
(fromfile "filename" (as string (drain:readc)))
```

**Comment by Kinnardian** [comment]
Thanks! I'll give that a try.
`fromfile` doesn't appear to appear in the documentation . . . though it's in the `help`.

**Comment by akkartik** [comment]
Yeah, `fromfile` is Anarki-only: http://arclanguage.org/item?id=12877

The online help doesn't help you know about new functions, sorry..

**Comment by zck** [comment]
I usually use "readline". It -- as you might expect -- reads a line at a time. I find this to be simpler to work with than `readc` or `readb`, as I usually want to work with either lines or words, and I think it's easier to parse words out of a line containing multiple words than try to build words out of characters one-by-one.

Example use:

    (fromfile "filepath" (drain (readline)))

This will give you a list of lines in the file.

**Comment by akkartik** [comment]
Ah, yes I forgot `readline`.

**Comment by akkartik** [comment]
Addendum to this statement of mine:

> The online help doesn't help you know about new functions, sorry..

I just remembered the CHANGES/ directory in the repo (
http://arclanguage.org/item?id=19686) and added a note to it about
`fromfile`: https://github.com/arclanguage/anarki/commit/575a02d3fa. I'll
keep adding to this directory as you pointing out things that aren't in the
documentation.
