### ISSUE TITLE
Distinction between peekc and readc

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#53]
What's the distinction between `peekc` and `readc`?

The documentation here implies that readc doesn't "leave the character for future reads": https://arclanguage.github.io/ref/io.html

This behavior doesn't seem to support that though:
```
arc> (= tesseract "squared square")
"squared square"
arc> (peekc (instring tesseract))
#\s
arc> (peekc (instring tesseract))
#\s
arc> (readc (instring tesseract))
#\s
arc> (readc (instring tesseract))
#\s
```

**Comment by shader** [comment]
You're constructing a new instring each time. Try saving it to a variable
and reusing that.

**Comment by Kinnardian** [comment]
Got it!:

```
arc> (= tesspipe (instring tesseract))
#<input-port:string>
arc> (peekc tesspipe)
#\s
arc> (peekc tesspipe)
#\s
arc> (readc tesspipe)
#\s
arc> (readc tesspipe)
#\q
```
Is there anywhere this "destructively reading from port" behavior is more generally described/defined? I take it this is the expected behavior independent of arc.

**Comment by akkartik** [comment]
Have you looked at the intro of https://arclanguage.github.io/ref/io.html
recently? Let me know if you still have any questions after reading it.
