### ISSUE TITLE
Permission denied; errno=13 on every request

### ISSUE THREAD

**Issue by fauria** [arclanguage/anarki#59]
HI!

I'm trying to run news.arc inside an Ubuntu 16.04 Docker container. I have everything set up and seems to be working, however after starting the server with `run-news` I get this response on every request to port 8080:

```
open-output-file: cannot open output file
  path: /anarki/www/logs/news-2016-11-06
  system error: Permission denied; errno=13
  context...:
    srvlog
    g13098
    g13097
    handle-request-thread
    handle-request-thread
open-output-file: cannot open output file
  path: /anarki/www/logs/srv-2016-11-06
  system error: Permission denied; errno=13
  context...:
    srvlog
```

I have checked permissions on `www/` directory, and even tried chmoding to 777 the whole path, but the error persists.

**Comment by akkartik** [comment]
Perhaps you need to create the directory called `/anarki/www/logs`?

**Comment by fauria** [comment]
Its already there:

```
# tree www/
www/
|-- admins
|-- logs
`-- news
    |-- profile
    |-- story
    `-- vote
```

**Comment by akkartik** [comment]
Can you share the output from `ls -lR` if it's not too long? What platform
are you on?

**Comment by fauria** [comment]
I'm inside an Ubuntu 16.04 Docker container in CoreOS:
```
# uname -a
Linux 629ea08ddff9 4.7.3-coreos-r2 #1 SMP Tue Nov 1 01:38:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
````

The content of `www` is that of my previous post:

```
# ls -lR www/
www/:
total 24
-rw-r--r--. 1 root root    7 Nov  6 15:59 admins
drwxr-xr-x. 2 root root 4096 Nov  6 16:00 logs
drwxr-xr-x. 5 root root 4096 Nov  6 16:00 news

www/logs:
total 0

www/news:
total 24
drwxr-xr-x. 2 root root 4096 Nov  6 16:00 profile
drwxr-xr-x. 2 root root 4096 Nov  6 16:00 story
drwxr-xr-x. 2 root root 4096 Nov  6 16:00 vote

www/news/profile:
total 0

www/news/story:
total 0

www/news/vote:
total 0
```

**Comment by akkartik** [comment]
Also for the parent directories all the way up.

**Comment by akkartik** [comment]
And for www/logs the directory rather than its contents.

**Comment by fauria** [comment]
It consists on pretty much this repo + tests:

https://gist.github.com/fauria/17d5d8522234dfe648908d6a95a448a2

**Comment by akkartik** [comment]
Ah, glad to hear it. What user is it running as? Perhaps you just needed to `chmod o+w /anarki/www/logs`.

**Comment by akkartik** [comment]
fauria edited 1008:
**Update:** Running `chmod -R 777 /anarki/` seems to solve the issue. Im
not sure exactly where the problem is, though.

**Comment by fauria** [comment]
Im running it as root, as it is a container. Ideally `www/` will be exposed as a volume to persist user generated data and logs.

**Comment by akkartik** [comment]
That's really strange then. I'll be curious if you're able to ever narrow the cause on a fresh container.

**Comment by fauria** [comment]
I guess this might have something to do with the following, after running `./run-news`:
`ps -ef`:
```
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 18:54 ?        00:00:00 /bin/bash
root        39     1  0 18:55 ?        00:00:00 /bin/bash ./run-news
root        40    39 95 18:55 ?        00:00:01 racket -t /anarki/boot.scm -e (aload (vector-ref (current-command-line-arguments
root        48     1  0 18:56 ?        00:00:00 ps -ef
```

wait a couple seconds and `ps -ef` again:

```
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 18:54 ?        00:00:00 /bin/bash
root        39     1  0 18:55 ?        00:00:00 /bin/bash ./run-news
bin         40    39 91 18:55 ?        00:00:06 racket -t /anarki/boot.scm -e (aload (vector-ref (current-command-line-arguments
root        54     1  0 18:56 ?        00:00:00 ps -ef
```

At some point, the `racket` process changes ownership -not sure how, though- to `bin` user, and that might be the reason why it permissions are denied for certain directories.

**Comment by akkartik** [comment]
Fascinating! Thanks for the updates.

**Comment by akkartik** [comment]
I just remembered why this happens: https://github.com/arclanguage/anarki/blob/b873b014c3/lib/srv.arc#L17. That `setuid` call has been in Arc since the beginning, but it's really kind of a hack. We don't usually run into a problem with it because we don't run as root. In a container it sounds like the ideal approach for you would be to `chgrp -R bin` and then `chmod -R g+w` your directory. Or you can just take that `setuid` line out :)

**Comment by fauria** [comment]
I found another issue.

If I export `www` as a volume (`VOLUME /anarki/www`) I get the following error:

```
arc> rename-file-or-directory: cannot rename file or directory
  source path: /anarki/tmp/cooks.14785459411478545941307
  dest path: /anarki/www/cooks
  system error: Invalid cross-device link; errno=18
  context...:
   /anarki/ac.scm:1168:13: mvfile
    signup-handler
    respond
    handle-request-thread
```

**Comment by akkartik** [comment]
The key there is whether the two paths are on the same file system or not. That's what the `Invalid cross-device link` is trying to say. If you plan to keep them on separate file systems you'll have to do a copy and move, which defeats the purpose of `rename-file-or-directory` (keeping the operation atomic).

Really every file system you create should have its own `tmp` space, so I'd suggest keeping both on a common file system.

Alternative approach: move `anarki/tmp` to `anarki/www/tmp`. Try editing `tmpdir*` at https://github.com/arclanguage/anarki/blob/b873b014c3/arc.arc#L2714. The drawback of this approach is that renames outside of `anarki/www` will now start to fail. Perhaps we need some sort of hook to use a different `tmpdir*` while running code in lib/app.arc and lib/news.arc.

**Comment by fauria** [comment]
I finally exported `anarki/www` as a whole and changed `arc.arc` on runtime. See https://github.com/fauria/docker-hn/blob/master/run.sh#L18

**Comment by akkartik** [comment]
Hi @fauria, could you try dropping that `sed` line in your `run.sh` script and see if things continue to work after my commit above? I'm hoping this is a cleaner solution.

**Comment by fauria** [comment]
Hi @akkartik! I just updated the script and It seems to work perfectly. Thank you!
