### ISSUE TITLE
`readall` stops prematurely if a top-level element is `nil`

### ISSUE THREAD

**Issue by zck** [arclanguage/anarki#61]
Tested on commit `e871d680cce6ed604aa8040ae51377f7e586971f`. This bug is also present in Arc 3.1.

```
arc> (readall "1 2 () 4")
(1 2)
```

I expected `'(1 2 nil 4)`. Similarly:

```
arc> (readall "1 2 nil 4")
(1 2)
```

Also I expected `'(1 2 nil 4)`. `readall` works as expected when the nil isn't at top-level:

```
arc> (readall "1 2 (()) 4")
(1 2 (()) 4)
arc> (readall "1 2 (nil) 4")
(1 2 (nil) 4)
```

**Comment by akkartik** [comment]
These read functions accept a configurable symbol to denote EOF:
https://arclanguage.github.io/ref/io.html#readline

**Comment by zck** [comment]
Yes, but even if you use a gensym, what actually prevents that symbol from being in the string?

Something seems to, but I'm not sure what:

```
arc> (uniq)
g3960
arc> (uniq)
g3961
arc> (readall "1 nil 3 g3962 5" (uniq))
(1 nil 3 g3962 5)
```

**Comment by akkartik** [comment]
This is an old trick from Common Lisp:

> *"`gensym` generates uninterned symbols, i.e., symbols that are not eq?, eqv?, or equal? to any other symbol, although they may print the same as other symbols."* (https://docs.racket-lang.org/reference/symbols.html)

(Arc's `uniq` is built from Racket's `gensym`.)

**Comment by akkartik** [comment]
Let me know if you have questions about interning. It's actually quite cool and worth understanding fully.

**Comment by zck** [comment]
Ah, interesting. I'll have to read through the code some more then, to really understand what's going on there.

Is there a particular reason the optional argument to `readall` *isn't` `(uniq)`, then?

**Comment by akkartik** [comment]
The caller needs to know precisely which gensym it is, so it can compare
with it :) Something like this:

```
(let eof (uniq)
  (if (is eof (readall (stdin) eof))
    ...))
```

There's no good way to encapsulate `(uniq)` perfectly behind the
abstraction.

...

Hmm, wait. We could replace the optional arg with a global:

```
(= eof (uniq 'eof))

(redef read ((o x (stdin)))
  (if (isa x 'string)
    (readstring1 x eof)
    (unserialize:sread x eof)))
```

We could also ripple the knowledge of the global through `readstring1` and
`sread` and everywhere else. That would be pretty clean. Hmm.

I just went looking in the Arc Tutorial (http://www.arclanguage.org/tut.txt)
and it doesn't show any calls to `read`. So even though this would be an
incompatible change, perhaps it's not breaking too much muscle memory.

Let me try making the change!

**Comment by akkartik** [comment]
/cc @rocketnia as a continuation of the conversation at
https://github.com/arclanguage/anarki/commit/8495169202afdcd02217b244a21a2381ff91ea7a#commitcomment-942297
.

**Comment by akkartik** [comment]
Try it out now, @zck!
