### ISSUE TITLE
Domain colours in news.arc

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#63]
When running `news.arc` and logged in as admin, when having made a submission, it is possible to click the domain name of the link as written in grey, which causes this text to change colour, first to red, then blue, then back to grey.
Does anyone know what those colours mean? Is it documented anywhere?

**Comment by akkartik** [comment]
Interesting feature; I hadn't seen it before.

Tracing through `lib/news.arc`, [`listpage`](https://github.com/arclanguage/anarki/blob/d0eb0dcf17/lib/news.arc#L844) calls [`display-items`](https://github.com/arclanguage/anarki/blob/d0eb0dcf17/lib/news.arc#L931) calls [`display-item`](https://github.com/arclanguage/anarki/blob/d0eb0dcf17/lib/news.arc#L1848), which [indirectly](https://github.com/arclanguage/anarki/blob/d0eb0dcf17/lib/news.arc#L1838) calls [`display-story`](https://github.com/arclanguage/anarki/blob/d0eb0dcf17/lib/news.arc#L964) calls [`titleline`](https://github.com/arclanguage/anarki/blob/d0eb0dcf17/lib/news.arc#L988). Finally, `titleline` has a [`tag-if`](https://github.com/arclanguage/anarki/blob/d0eb0dcf17/lib/news.arc#L1007) which shows this functionality, toggling sites through "ignore" and "kill". For what these terms mean, see [here](https://github.com/arclanguage/anarki/blob/d0eb0dcf17/lib/news.arc#L1596). Killing a site automatically kills all stories submitted from it. Ignoring a site kills stories *and* ignores submitters, thereby auto-killing all subsequent stories submitted by them.

**Comment by hjek** [comment]
Added it to the docs.
