### ISSUE TITLE
Scribd links on PDF-files

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#64]
In `news.arc` submissions with links to pdf-files have links to viewing on **Scribd**. What is the use case for this functionality? JavaScript-capable browsers like Chromium and Firefox can already read PDFs.

Wouldn't it be reasonable to disable it by default, or have a clear option to disable it? Is this **Scribd** not a bit like **Pocket** in Firefox or **Amazon Search** in Ubuntu, in that it connects to 3rd party and is enabled by default?

I can probably submit a patch, if it is agreeable to disable it by default.

**Comment by akkartik** [comment]
Yes please! Thanks for suggesting this. I would also be happy to rip out this functionality entirely. We don't have much manpower to support bug reports so less code is always better.

**Comment by zck** [comment]
This functionality, IIRC, predates browsers being able to read pdfs. It's probably not especially useful now, as you mentioned. I'd also be fine removing it entirely.

**Comment by hjek** [comment]
Great. It is out now.

I could imagine some other file type sensitive functionality that would be useful though.

**Comment by akkartik** [comment]
Thanks! I made a [minor tweak](https://github.com/arclanguage/anarki/commit/53cf5f91e6).
