### ISSUE TITLE
Only a limited number of submissions show up in news.arc

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#67]
At the bottom of the front page of a running `news.arc` instance, there is a **More** link that navigates to the next page. However, *on that next page* the **More** button is not present, even when there are enough submissions to fill many pages.

**Comment by akkartik** [comment]
Thanks for the report! I'll take a look in a day or two (we had twins recently, so life has gotten busy). Do update the bug if you are able to figure out what the issue is.

**Comment by hjek** [comment]
Congrats with twins!

Yes, posting this bug is also partly a note-to-self to have a look at it. **Arc Language Forum** doesn't seem to have the same issue.

**Comment by akkartik** [comment]
Thanks, yeah if recent history is any guide it's probably a regression I introduced.

**Comment by akkartik** [comment]
Hmm, I'm having trouble reproducing this. I can see 'More' links on both page 1 and page 2 of both the frontpage and /newest. See screenshots (using Anarki head, after modifying `perpage*` to 3 stories per page).

![1](https://user-images.githubusercontent.com/3161/30993990-698bb25a-a466-11e7-8f4e-6cd50e0a9397.png)

![2](https://user-images.githubusercontent.com/3161/30993989-6989fd8e-a466-11e7-8c96-8c8e4497c59f.png)

**Comment by hjek** [comment]
I had modified the `perpage*` to be 90, and with that value, it showed the first 180 out of ~600. So, ok, this is not the **More** button missing, but rather *a lot of submissions missing*.

This happens on the front page as well as on the list of submissions of a user.

Is there perhaps some *time limit* after which the submissions are not shown anywhere?

These "hidden" submissions are still present in `anarki/www/news/story`, and can still be navigated to by typing in their id in the url, but they are absent from all listings.

**Comment by akkartik** [comment]
Hmm, I do see that the /top page has [a limit of 180 by default](https://github.com/arclanguage/anarki/blob/c3849efaf9/lib/news.arc#L307).

> Is there perhaps some *time limit* after which the submissions are not shown anywhere?

It doesn't look like it, looking at [`latest-items`](https://github.com/arclanguage/anarki/blob/c3849efaf9/lib/news.arc#L319). It just grabs the most recent items, without regard to their timestamps.

**Comment by hjek** [comment]
Strangely, when I change all the occurances of `180` to `500`, the 180 limit remains.
I'll need to twiddle around with the numbers in `news.arc` to see which one is *really* deciding that limit.

**Comment by akkartik** [comment]
Good idea. Also worth figuring out if the limit is 180 or some lower number. Try setting `perpage*` to 180 and check if the first page loses the 'More' link. Then try tweaking it downward and see what value it appears at.

**Comment by hjek** [comment]
You were right about setting the numbers, but it just didn't take immediate effect because of caching.
I'll increase the defaults, because they are currently unreasonably low.
