### ISSUE TITLE
No search bar

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#69]
`news.arc` doesn't have a search bar, like [**Hacker News**](https://news.ycombinator.com) has.

**Comment by akkartik** [comment]
This is so awesome you've got me hacking on it now. Look out for a few commits.

**Comment by hjek** [comment]
Nice. Looking forward to the new things.

The search bar was surprisingly easy to write. Less than a screenful of code.

It's probably not able to search through millions of submissions, like **"HN Search powered by Algolia"**, but at least this one works without (non-free) JavaScript.

**Comment by akkartik** [comment]
Yup! I just pushed a few commits. Check them out, and comments/corrections/reversions most welcome.

**Comment by akkartik** [comment]
What did you think of my changes?

**Comment by hjek** [comment]
They're wonderful! Nice to get some feedback on the code.

**Multi-word search** makes it behave more like other search engines. Great.

Interesting to see some **arcisms** in use, like *square bracket+underscore syntax*. I had to look up what `tokens`, `idfn`, `some` and `all` meant, and I'd forgotten how neat that *interactive help subsystem* is.

I don't know why I left that `newsop` in there. I guess I thought it was something that "you had to do."

**Thanks for hacking on this, too!**
