### ISSUE TITLE
append doesn't append

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#71]
`append` doesn't append.

This is what `append` does in **Racket**,

    > (append '(a b) '(c d))
    '(a b c d)

That makes sense to me.

This is what `append` does in **arc**,

    arc> (append '(a b) '(c d))
    (c d)
    arc> (help append)
    [fn]  (append l tail)
    append is not documented.

`join` does the job, though,

    arc> (join '(a b) '(c d))
    (a b c d)

What is the deal with `append` in **arc**?

**Comment by akkartik** [comment]
That was indeed a puzzle. The key turned out to be to go find where `append` was defined, and lo it was me in https://github.com/arclanguage/anarki/blob/b19fe33c6f/lib/spliceable-list.arc#L24. Turns out I made `append` destructive. Perhaps I should call it `append!`?

**Comment by akkartik** [comment]
Perhaps I should call it `join!`, and preserve the existing naming scheme.

**Comment by hjek** [comment]
*That* explains it. Yes, `join!` is more appropriate. And perhaps also no (or `nil`) return value would be less confusing?

**Comment by akkartik** [comment]
Ack, exclamation marks don't work because they get interpreted as ssyntax. Perhaps I'll just use the Common Lisp `njoin`.

**Comment by hjek** [comment]
That would explain the absence of the `!` in the first place. `njoin` is clearer than `append`, and doesn't clash with anything from **Racket**. And I see you documented it too. Nice.
