### ISSUE TITLE
Error when accessing blog archive

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#74]
When accessing the blog archive at `http://localhost:8080/archive`, I get the following error,

```
Can't coerce  nil fn
  context...:
   /home/pelle/anarki/ac.scm:1026:0: ar-coerce
    g20313
    recur
    g20313
    g20312
    handle-request-thread
   [repeats 1 more time]

```

It looks like the blog is being displayed correctly, except that there's a • too many.

**Comment by akkartik** [comment]
Looks like this is another name conflict between news.arc and blog.arc. Perhaps you have some items in the news side?

We probably want separate `maxid*` variables for `postdir*` in blog.arc and `storydir*` in news.arc.

**Comment by hjek** [comment]
You were right about that. Lexical scoping is weird.

**Comment by akkartik** [comment]
Hmm, it doesn't have to do with lexical scope as far as I can see. `maxid*` is a regular global variable, so we're just dealing with standard issues around globals. Am I missing something?

**Comment by hjek** [comment]
Maybe I got the words wrong. I thought that *lexical scoping* means that variables are defined globally, whereas *dynamic scoping* is local to the function or module or whatever.

But yes, it is *the standard issue about globals*, and it's an issue that would not exist in Racket because variables from different files/modules can't clash there.

**Comment by akkartik** [comment]
Lexical scope basically means that a mentions of a variable refer to bindings created *nearby in the code*. Dynamic scope means mentions of a variable refer to the most recently created binding *at runtime*. Lexical scope is made using `let` in Racket and Arc. And as you can see in `arc.arc`, `let` is just syntax sugar for a function call, showing that function parameters are bound lexically by default. That was [Scheme's #1 original idea](https://en.wikipedia.org/wiki/Scheme_(programming_language)#Lexical_scope).

Globals are an independent axis. In Common Lisp you can create regular lexically-scoped globals using just regular `setf` and `setq`, or dynamically-scoped *special* variables using `defvar` or `defparameter`. Ok, perhaps it's not a completely independent axis. Making local variables dynamically scoped is a bad idea, so nobody does that anymore (except off-brand Lisps like [Newlisp](http://www.newlisp.org/newlisp_manual.html#scoping). Dynamic variables today are always global, so you don't mix local *scope* with dynamic [*extent*](https://www.cs.cmu.edu/Groups/AI/html/cltl/clm/node43.html). 'Scope' vs 'extent', incidentally, is a cleaner way to think about this than 'local' vs 'global'.

I don't know how clear this is, so [here's another description](http://www.gigamonkeys.com/book/variables.html).

**Comment by hjek** [comment]
Thanks for the link! I think I get the ideas somehow, but not really the words.

So I guess lexical scope is what you use for closures, and dynamic scope is like shell scripting and stuff. PG writes that [Emacs Lisp has dynamic scope](http://paulgraham.com/thist.html) though!
