### ISSUE TITLE
Users can edit each other's blog posts

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#75]
Not sure whether it's a bug or a feature.

**Comment by hjek** [comment]
On the **blog**, literally anyone could create a user and *instantly delete all posts*.

I take this to mean that no one was actually using **blog** as it was, and that it is therefore probably okay that I change the **blog** to include some features from **news**, which means that sadly the **blog** can not run independently of **news**, but will be more secure and usable at least.

**Comment by akkartik** [comment]
I don't think blog.arc was ever intended as a real app. http://www.arclanguage.org/tut.txt calls it a sample program. So yes, rock on!

**Comment by hjek** [comment]
Cool. It's almost a real app now.
