### ISSUE TITLE
REPL history doesn't work with news.arc

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#77]
When launching `run-news`, the REPL history doesn't work (e.g. pressing `up arrow` to see previous expression). It works, however, when running **arc** via `arc.sh`. Perhaps `rlwrap` is not being loaded correctly.

**Comment by akkartik** [comment]
Good catch. It's because `arc.sh` doesn't use `rlwrap` when invoked with a file to load, as it is in `lib/run-news.arc`.

I'm not sure how to fix this. Let's think on it.

**Comment by akkartik** [comment]
I suppose that works for starters. We'll see what issues that runs into..
