### ISSUE TITLE
`admin` op is broken

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#84]
When going to `http://localhost:8080/admin` and entering any name and password, **Anarki** replies `Bad data.`

This `admin` op works fine in **Arc 3.1**.

**Comment by hjek** [comment]
This one is difficult to check using `git bisect`, because many of the past commits are from when there was an issue with temporary folders that completely broke login.

**Comment by akkartik** [comment]
Sometimes it's just easier to grep for "Bad data" and then run `git log -p` for lib/app.arc 😄 The culprit is this change of mine: c984408fec. It started requiring an email when creating accounts, but the admin page isn't setting up an email.

I'm not sure this is worth fixing. Do you care if I just delete that page altogether?

**Comment by hjek** [comment]
If an admin wants to make a user, they can just use the sign up form. I don't see why that page is necessary at all (except for being able to create users w/o loading **news**, but no-one does that)

**Comment by hjek** [comment]
It's just because there is a lot of hidden or unused functionality in this repo. Some of this hidden code is quite nice, but some of it is useless. Worth going through it, though!

For example, do you have *any* idea how `arcscript.arc` works? Would be really cool if it *did* work.

And `re.arc` is confusingly *not* used for the regexps in **Arc**; rather`strings.arc` is. `re.arc` currently doesn't work.

**Comment by akkartik** [comment]
Looks like `arcscript.arc` was never working: https://github.com/arclanguage/anarki/commit/d8e69d14aa

:)

I think situations like this (and `re.arc`) are natural in Anarki given it's a communal testbed for experiments. It chose to err on the side of being more accepting (there's lots of other projects that err on the side of working :o) One important signal to attend to is whether a file is loaded in `libs.arc`.

Using Anarki in a real app is always going to require paying attention to new commits before pulling them to your copy.

**Comment by hjek** [comment]
Makes sense having a place for all the experiments.
