### ISSUE TITLE
Repl is slow to boot

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#86]
The repl takes quite a while to boot up. I know it said "takes ~4s to start", but it's more like 80 seconds on my modest laptop. A lot slower than **Arc 3.1**.

**Comment by akkartik** [comment]
That sucks, yes definitely worth improving.

One obvious thing I can think of is that we load a lot more code. There is a lot more code, and we load it up front unlike Arc 3.1 which has a more on-demand attitude toward a lot of it.
