### ISSUE TITLE
Locked stories can't be unlocked

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#87]
In News, when an admin edits a post (by another user), this post becomes locked. (This is visible in the `keys` section when editing a story as admin.)

If an admin then wants to unlock a story, to allow this other user to edit the story again, then that is *not possible*, because if the `locked` key is deleted from `keys`, then it is placed there again once the **update** button is pressed.

It should be possible for admins to edit stories of users *without locking them*, for example to correct spelling mistakes or typos.

**Comment by akkartik** [comment]
I see that now. https://github.com/arclanguage/anarki/blob/b3a6a43005/lib/news.arc#L1954

I think the goal may have been to keep users from reverting admin changes. HN has so little a user can edit already. The URL is fixed, so it's just the title. If an admin modifies the title they don't want it changed again.

What sorts of scenarios are you considering where you want to allow users to continue editing?

**Comment by hjek** [comment]
There's the scenario where a story has text and no URL, for example a **Show HN**-like story. If an admin is correcting a typo in the text, the whole thing gets locked down with no way of unlocking it.

**Comment by akkartik** [comment]
Ah, makes sense.
