### ISSUE TITLE
Unable to run under FreeBSD 11.1 on Racket 6.12

### ISSUE THREAD

**Issue by matthewwiese** [arclanguage/anarki#96]
When I run `sh arc.sh` in the anarki repository, the script does not run and I am greeted with the message:

`arc.sh: [[: not found`
`Sorry, this script doesn't run on your platform FreeBSD yet. Please create a new issue at https://github.com/arclanguage/anarki/issues.`

~~I'm fairly new to FreeBSD so perhaps this is a vanilla response. Nevertheless, I'm not entirely sure how to get it working myself.~~

EDIT: Just checked the arc.sh file and realized that this is a message from the script, not my system.

**Comment by akkartik** [comment]
The error seems unnecessarily heavyhanded. All that `case` block is doing is installing Racket and rlwrap. Can you try installing Racket, then commenting out the error message and exit, then running it from the top-level directory for Anarki? Instead, make it look like this:

```
*)
    arc_dir=$(pwd)
```

You may still run into issues. The error above about `[[: not found` suggests that you may need to [explicitly install bash](https://www.freebsd.org/doc/en_US.ISO8859-1/articles/linux-users/shells.html).

**Comment by matthewwiese** [comment]
Thank you for the assistance akkartik. The `[[: not found` error didn't immediately occur to me to be a shell error. Will try to figure that issue out (as I do have bash installed and running).

Should your change to the catchall be added to the repository? From your comment it sounds like your fix should be the default for users.

**Comment by akkartik** [comment]
Yes, once you can confirm you get it working I'll send you a PR.

**Comment by matthewwiese** [comment]
Hey @akkartik I made the change and everything works fine when I run `bash arc.sh`!

The only problem is to execute `./arc.sh` directly I have to change the first line to `#!/usr/local/bin/bash` but that's just because I have it installed there on my system. My suggestion is to make it more explicit in the README for users of other Unix variants -- perhaps a little blurb much like your comment to me telling users to make sure they are using the correct shell and that it's assumed bash is located at `/bin/bash`?

**Comment by akkartik** [comment]
Awesome! Does FreeBSD have `/usr/bin/env`?

**Comment by matthewwiese** [comment]
Yes it does! I see where you're going with this... change the shebang to `#!/usr/bin/env bash`?

**Comment by akkartik** [comment]
Thanks for https://github.com/arclanguage/anarki/pull/97!

**Comment by akkartik** [comment]
A coda on "standard paths":

* Darwin doesn't have `/usr/bin/zsh`, only `/bin/zsh`.
* OpenBSD doesn't have `/bin/zsh`, only `/usr/bin/zsh`.
* FreeBSD doesn't have `/bin/bash`, only `/usr/local/bin/bash`.

[Looks like POSIX is silent on where utilities should be located.](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap10.html) ([Though perhaps it wasn't always thus?](http://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xbd_chap10.html))

Everyone has `/usr/bin/env`, but that's considered insecure. What is a sophont to do?
